/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Total Mazes Completed": "完成的迷宫总数",
    "Total Points Earned": "获得的总点数",
    "Total Remember Last Pathways": "总计记住最后的途径",
    "Total Spent": "总花费",
    "Total Tiles Revisited": "重新访问的总瓷砖数",
    "Total Time in Current Biome": "当前生物群落的总时间",
    "Total Time Played": "总游戏时长",
    "Unlock All Items": "解锁所有物品",
    "Total Unique Tiles Visited": "访问过的独特瓷砖总数",
    "Unlock All Upgrades": "解锁所有升级",
    "Unlocking new biomes is how you progress through the game to unlock more upgrades, fancier mazes, and higher point rewards. \n          This should generally be your priority, but you do you.": "解锁新的生物群落是您在游戏中取得进展以解锁更多升级、更精美的迷宫和更高点数奖励的方式。 \n 这通常应该是你的首要任务，但是得你自己做。",
    "Unlocks the Toggle Panel which allows you to enable/disable bot functionality.": "解锁允许您启用/禁用机器人功能的切换面板。",
    "Up: 'Up Key' or 'W'": "向上：“向上键”或“W”",
    "UpgradeType": "升级类型",
    "Visited Tiles": "访问的瓷砖",
    "WARNING: This is non-reversible and will delete your current save. Recommend you save again first!": "警告：这是不可逆的，将删除您当前的存档。 建议您先导出存档后，再尝试！",
    "WARNING: Your saved game is from an older version!": "警告：您存档的游戏来自旧版本！",
    "Welcome to A Mazing Idle!": "欢迎来到 神奇放置在哪里！",
    "Welcome Back to A-Mazing-Idle!": "欢迎回来 神奇放置在哪里！",
    "Welcome back!) Game content and save data may not work as expected. Major changes have been made!": "欢迎回来！）游戏内容和存档数据可能无法按预期工作。 发生了重大变化！",
    "When a bot is within X non-walled tiles of the maze exit, it will automatically navigate to the exit.": "当机器人在迷宫出口的 X 无墙瓷砖内时，它会自动导航到出口。",
    "When a bot merge occurs, the resulting direction of the bot will be away from deadends.": "当机器人合并发生时，机器人的最终方向将远离死胡同。",
    "When bot is at a decision point, he will remember what pathway was not visited last time and prioritize it next time at the decision point. Only one decision point can be remembered.This helps avoid getting stuck in back and forth deadend loops.": "当机器人处于决策点时，他会记住上次没有访问过的路径，并在下次决策点优先考虑它。 只能记住一个决策点。这有助于避免陷入来回死胡同。",
    "When bot is faced with a choice of direction, the bot will be lucky in guessing direction by an extra 1% (ie. 51%/49% of choosing correct direction at level 1).": "当 机器人 面临方向选择时，机器人 将幸运地猜测方向 1%（即在第 1 级选择正确方向的 51%/49%）。",
    "When bots step on the same tile, they will merge together and re-split at next unvisited tile split.If bots have not found an unvisited tile within 15 tiles, they will forcefully split.": "当机器人踩到同一个图块时，它们会合并在一起并在下一个未访问的图块拆分时重新拆分。如果机器人在 15 个图块内没有找到未访问的图块，它们将强制拆分。",
    "When none of the active bots find an unvisited tile after X tiles, they will move Y speed faster.": "当没有一个活跃的机器人在 X 块之后找到未访问的块时，它们会以更快的速度移动 Y。",
    "Speed Ups Used": "使用的加速",
    "SQUARE": "正方形",
    "Stats": "统计",
    "STAIRCASE": "楼梯",
    "Total": "总计",
    "Total Bot Merges": "机器人合并总数",
    "Total Bot Splits": "机器人拆分总数",
    "Total Dead Ends Marked": "标记的总死胡同",
    "Total Destructible Walls Destroyed": "被破坏的可破坏的墙壁总数",
    "Total Lucky Guesses": "幸运猜想总计",
    "Tile Multiplier Points": "瓷砖乘数点",
    "Tile Count": "瓷砖数量",
    "That said, you do you friend!  Good luck!": "那就是说，你是你的朋友！ 祝你好运！",
    "Import Save (No Going Back!": "导入存档（没有回头路！",
    "Increase the frequency by which a bot can phase through destructible walls.": "增加机器人穿越可破坏墙壁的频率。",
    "Left: 'Left Key' or 'A'": "往左：“左键头”或“A”",
    "Manual Movement!": "手动移动！",
    "Max Maze Iterations": "最大迷宫迭代",
    "Maze Algorithm": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Unlock Experiments Panel: ": "解锁实验面板：",
    "Unlock Toggle Panel: ": "解锁切换面板：",
    "Wall Phasing Frequency: ": "墙壁移相频率：",
    "Teleport bot to player: Q (must be unlocked": "传送机器人到玩家：Q（必须解锁",
    "Import Save JSON": "导入存档JSON",
    "Maze Algorithm: ": "迷宫算法：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "maze keys found": "找到迷宫钥匙",
    "pts/s": " 点数/秒",
    "tiles visited": " 访问过的瓷砖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+):([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Wall Phasing Total Storage (4 ➔ 6): 10,000 pts$/, '墙壁相位总存储 $1：$2 点数'],
    [/^Unlock New Biome (.+): (.+) pts$/, '解锁新生物群落 $1：$2 点数'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);